#!/bin/bash

# Build docker image
git clone https://github.com/iamale/dokku-rabbitmq-webstomp-dockerfiles.git /tmp/dokku-rabbitmq-dockerfiles
docker build -t iamale/rabbitmq-webstomp /tmp/dokku-rabbitmq-dockerfiles
rm -rf /tmp/dokku-rabbitmq-dockerfiles
